// BirthRegistrationForm.Layout.cs - screen-fitting layout, readable type and inline field messages.
//
// Presentation only. Nothing in here touches SQL, the save path or the business rules; it decides
// how big the entry window is, how large the text is, and where a "please fix this" sentence
// appears. Kept out of the Designer on purpose: this form's Designer file has been regenerated by
// Visual Studio before and silently dropped hand-added controls.

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using CROMS.Data;
using CROMS.Modules;

namespace CROMS.Forms
{
    public partial class BirthRegistrationForm
    {
        // ------------------------------------------------------------------ type scale (pixels)
        // Pixel-based so the size means the same thing on every machine. A label is 19, what you type
        // is 20, a button 22, a section heading 24, the page title 32. The small hint under a
        // dropdown and a validation sentence are the only things allowed below 19.
        private const float PxTitle = 32f, PxSub = 18f, PxLabel = 19f, PxInput = 20f, PxButton = 22f,
                            PxHint = 16f, PxErr = 17f, PxGrid = 18f;

        /// <summary>A pixel-sized Segoe UI font.</summary>
        private static Font Px(float px, FontStyle st = FontStyle.Regular)
        {
            return new Font("Segoe UI", px, st, GraphicsUnit.Pixel);
        }

        private static float PxOf(Font f)
        {
            return f.Unit == GraphicsUnit.Pixel ? f.Size : f.SizeInPoints * 96f / 72f;
        }

        // ------------------------------------------------------------------ state
        private const int ErrH = 24;      // height reserved under a field that can show a message
        private const int InputPad = 6;      // the input's own 3px margin above and below
        private const int CapH = 22;      // the small caption under each dropdown of a place
        private int _inputH = 34;         // natural height of a one-line input at PxInput
        private int _appliedKey = -1;     // tier + width class last laid out, so a resize storm is cheap
        private bool _fontsApplied;
        private TableLayoutPanel _entryRoot;
        private FlowLayoutPanel _entryFooter;
        private TableLayoutPanel _wizardBody, _wizardRoot;

        /// <summary>Marks a place-of-birth style host so the layout pass can resize it.</summary>
        private const string LookupCaptioned = "lookup:cap";
        private const string LookupPlain = "lookup:plain";

        private sealed class FieldMsg
        {
            public Label Text;
            public TableLayoutPanel Wrap;
            public TableLayoutPanel Table;
            public int Row;
        }

        private readonly Dictionary<Control, FieldMsg> _fieldMsgs = new Dictionary<Control, FieldMsg>();

        private TableLayoutPanel[] EntryTables()
        {
            return new[] { tblChild, tblMother, tblFather, tblMarriage, tblAttendant, tblInformant, tblCert };
        }

        // ------------------------------------------------------------------ entry window size
        /// <summary>
        /// The popup takes most of the usable screen - 92% of it, 97% on a short one such as
        /// 1366x768 - and is centred. It never asks for more than the screen has.
        /// </summary>
        internal static Size EntryDialogSize(Rectangle workArea)
        {
            double wFrac = workArea.Width < 1500 ? 0.97 : 0.92;
            double hFrac = workArea.Height < 900 ? 0.97 : 0.92;
            int w = Math.Min(workArea.Width, Math.Max(900, (int)(workArea.Width * wFrac)));
            int h = Math.Min(workArea.Height, Math.Max(600, (int)(workArea.Height * hFrac)));
            return new Size(w, h);
        }

        // ------------------------------------------------------------------ inline field messages
        /// <summary>
        /// Gives an input a sentence-sized slot directly underneath it. The input moves into a small
        /// two-row wrapper that takes its cell: input on top, a (normally empty) red line below.
        /// The slot is reserved, so showing or clearing a message never moves anything else.
        /// </summary>
        private void PrepareFieldMessages()
        {
            if (_fieldMsgs.Count > 0) return;
            Control[] inputs =
            {
                txtFirstName, txtLastName, cboSex, dtpDob, dtpMarrDate,
                dtpAttDate, dtpInfDate, dtpPreparedDate, dtpReceivedDate, dtpRegisteredDate,
                txtFee, txtFeeOr
            };
            foreach (Control input in inputs) AttachFieldMessage(input);
        }

        private void AttachFieldMessage(Control input)
        {
            var tbl = input.Parent as TableLayoutPanel;
            if (tbl == null) return;
            TableLayoutPanelCellPosition cell = tbl.GetPositionFromControl(input);
            int span = tbl.GetColumnSpan(input);
            int tab = input.TabIndex;

            var wrap = new TableLayoutPanel
            {
                ColumnCount = 1,
                RowCount = 2,
                Margin = new Padding(0),
                Padding = new Padding(0),
                Dock = DockStyle.Top,
                BackColor = Color.Transparent,
                Height = _inputH + InputPad + ErrH
            };
            wrap.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            wrap.RowStyles.Add(new RowStyle(SizeType.Absolute, _inputH + InputPad));
            wrap.RowStyles.Add(new RowStyle(SizeType.Absolute, ErrH));

            var msg = new Label
            {
                AutoSize = false,
                AutoEllipsis = true,
                Dock = DockStyle.Fill,
                ForeColor = UiTheme.Danger,
                Font = Px(PxErr),
                TextAlign = ContentAlignment.TopLeft,
                Margin = new Padding(Math.Max(0, input.Margin.Left), 2, 0, 0),
                Visible = false,
                UseMnemonic = false
            };

            tbl.Controls.Remove(input);
            input.Anchor = input.Anchor | AnchorStyles.Top;
            wrap.Controls.Add(input, 0, 0);
            wrap.Controls.Add(msg, 0, 1);
            tbl.Controls.Add(wrap, cell.Column, cell.Row);
            if (span > 1) tbl.SetColumnSpan(wrap, span);
            wrap.TabIndex = tab;

            _fieldMsgs[input] = new FieldMsg { Text = msg, Wrap = wrap, Table = tbl, Row = cell.Row };

            // The message goes the moment the field changes - the clerk is fixing it.
            Action clear = () => ClearFieldMessage(input);
            if (input is TextBox) ((TextBox)input).TextChanged += (s, e) => clear();
            else if (input is ComboBox)
            {
                ((ComboBox)input).SelectedIndexChanged += (s, e) => clear();
                ((ComboBox)input).TextChanged += (s, e) => clear();
            }
            else if (input is DateTimePicker) ((DateTimePicker)input).ValueChanged += (s, e) => clear();
        }

        /// <summary>
        /// Shows one short red sentence under <paramref name="input"/>. Pass the sentence in order of
        /// preference, longest first: the first one that fits the column is used, so the text is never
        /// cut off.
        /// </summary>
        private void ShowFieldMessage(Control input, params string[] variants)
        {
            FieldMsg m;
            if (variants == null || variants.Length == 0 || !_fieldMsgs.TryGetValue(input, out m)) return;
            string pick = variants[0];
            int room = m.Wrap.Width - m.Text.Margin.Left - 4;
            if (room > 60)
            {
                pick = variants[variants.Length - 1];
                foreach (string v in variants)
                    if (TextRenderer.MeasureText(v, m.Text.Font, new Size(int.MaxValue, ErrH), TextFormatFlags.NoPadding).Width <= room)
                    { pick = v; break; }
            }
            m.Text.Text = pick;
            m.Text.Visible = true;
        }

        private void ClearFieldMessage(Control input)
        {
            FieldMsg m;
            if (_fieldMsgs.TryGetValue(input, out m) && m.Text.Visible)
            {
                m.Text.Visible = false;
                m.Text.Text = "";
            }
        }

        private void ClearAllFieldMessages()
        {
            foreach (Control input in _fieldMsgs.Keys.ToList()) ClearFieldMessage(input);
        }

        /// <summary>Brings a field into view and puts the cursor on it.</summary>
        private void FocusField(Control input, TabPage tab)
        {
            if (tab != null && tabControl.SelectedTab != tab)
            {
                tabControl.SelectedTab = tab;
                UpdateStepNavigation();
            }
            // A field inside a scrolling tab page may be below the fold.
            for (Control p = input.Parent; p != null; p = p.Parent)
            {
                var sc = p as ScrollableControl;
                if (sc != null && sc.AutoScroll) { sc.ScrollControlIntoView(input); break; }
            }
            input.Focus();
        }

        // ------------------------------------------------------------------ type + sizes
        /// <summary>Sets the readable type scale on everything in the entry tabs.</summary>
        private void StyleEntryFonts(Control parent)
        {
            foreach (Control c in parent.Controls)
            {
                // These paint their own text (or have none); they get the scale through their own switch.
                if (c is StepStrip || c is IssueList || c is Banner || c is ToggleSwitch || c is StatusPill) continue;

                if (c is TextBox || c is ComboBox || c is DateTimePicker || c is NumericUpDown || c is MaskedTextBox)
                    c.Font = Px(PxInput);
                else if (c is Label || c is CheckBox || c is RadioButton || c is LinkLabel)
                {
                    float cur = PxOf(c.Font);
                    // Small hints (under a dropdown) become the hint size; headings already larger stay.
                    float target = cur <= 11.5f ? PxHint : (cur >= 24f ? cur : PxLabel);
                    c.Font = Px(target, c.Font.Style);
                }

                if (c is DateTimePicker && (c.Anchor & AnchorStyles.Right) == 0)
                    c.Width = Math.Max(c.Width, 270);   // a dd/mm/yyyy date plus its tick box and arrow

                if (c.HasChildren) StyleEntryFonts(c);
            }
        }

        private int MeasureInputHeight()
        {
            int h = 0;
            foreach (Control c in new Control[] { txtFirstName, cboSex, dtpDob })
            {
                if (c == null) continue;
                h = Math.Max(h, c.PreferredSize.Height);
            }
            return Math.Max(34, h);
        }

        /// <summary>
        /// Applied once, the first time the popup opens: fonts, the measured input height, and the
        /// sizes that follow from it (the reserved message line, the place dropdown hosts).
        /// </summary>
        private void ApplyEntryFontsOnce()
        {
            if (_fontsApplied) return;
            _fontsApplied = true;

            tabControl.SuspendLayout();
            foreach (TabPage p in tabControl.TabPages)
            {
                p.AutoScroll = true;
                p.Padding = new Padding(24, 18, 24, 18);
            }
            StyleEntryFonts(tabControl);
            _inputH = MeasureInputHeight();

            foreach (FieldMsg m in _fieldMsgs.Values)
            {
                m.Wrap.RowStyles[0].Height = _inputH + InputPad;
                m.Wrap.RowStyles[1].Height = ErrH;
                m.Wrap.Height = _inputH + InputPad + ErrH;
                m.Text.Font = Px(PxErr);
            }
            tabControl.ResumeLayout(true);
        }

        /// <summary>
        /// Spacing that follows the height we were given. A tall window gets roomy rows; a short one
        /// (1366x768) falls to tighter rows - the text size never changes. Below what even the tightest
        /// rows need, the tab simply scrolls rather than squashing.
        /// </summary>
        private void ApplyEntryTier()
        {
            if (_entryDialog == null || !_fontsApplied) return;
            Size cs = _entryDialog.ClientSize;
            int tier = cs.Height >= 900 ? 0 : cs.Height >= 780 ? 1 : 2;
            int wide = cs.Width >= 1500 ? 1 : 0;
            int key = tier * 10 + wide;
            if (key == _appliedKey) return;
            _appliedKey = key;

            int gap = tier == 0 ? 18 : tier == 1 ? 12 : 9;

            _entryDialog.SuspendLayout();
            tabControl.SuspendLayout();
            foreach (TableLayoutPanel t in EntryTables())
            {
                // Label columns are as wide as their widest caption, so every field lines up and no
                // caption wraps or is cut.
                foreach (int col in new[] { 0, 2 })
                {
                    if (col >= t.ColumnStyles.Count) continue;
                    int w = 0;
                    foreach (Control c in t.Controls)
                    {
                        if (!(c is Label) || t.GetColumn(c) != col) continue;
                        w = Math.Max(w, TextRenderer.MeasureText(c.Text ?? "", c.Font, new Size(int.MaxValue, 100), TextFormatFlags.NoPadding).Width);
                    }
                    t.ColumnStyles[col].SizeType = SizeType.Absolute;
                    t.ColumnStyles[col].Width = w == 0 ? 24 : Math.Max(150, Math.Min(330, w + 28));
                }

                for (int r = 0; r < t.RowCount && r < t.RowStyles.Count; r++)
                {
                    bool hasMsg = false, captioned = false, memo = false;
                    var kids = new List<Control>();
                    foreach (Control c in t.Controls) if (t.GetRow(c) == r) kids.Add(c);
                    foreach (Control c in kids)
                    {
                        TableLayoutPanel w = c as TableLayoutPanel;
                        if (w != null && _fieldMsgs.Values.Any(m => m.Wrap == w)) hasMsg = true;
                        Panel p = c as Panel;
                        if (p != null && (p.Tag as string) == LookupCaptioned) captioned = true;
                        TextBox tb = c as TextBox;
                        if (tb != null && tb.Multiline) memo = true;
                    }

                    int h = _inputH + gap;
                    if (hasMsg) h += ErrH;
                    else if (captioned) h += CapH;
                    if (memo) h = Math.Max(_inputH * 3, 120) + gap;
                    t.RowStyles[r].SizeType = SizeType.Absolute;
                    t.RowStyles[r].Height = h;

                    // A row whose input carries a line underneath is aligned to the TOP so the caption
                    // stays level with the input rather than centred between input and message.
                    bool top = hasMsg || captioned || memo;
                    foreach (Control c in kids) AlignInRow(c, top);
                }

                // A Dock=Top table does not grow with its rows; without this everything past the old
                // designed height (weight, place of birth ...) is cut off.
                int total = 0;
                for (int r = 0; r < t.RowCount && r < t.RowStyles.Count; r++) total += (int)t.RowStyles[r].Height;
                t.Height = total + t.Padding.Vertical + 8;

                // Ordinary single-line dropdown hosts (citizenship, religion ...): same height as an input.
                foreach (Control c in t.Controls)
                {
                    Panel p = c as Panel;
                    if (p == null) continue;
                    string tag = p.Tag as string;
                    if (tag != LookupCaptioned && tag != LookupPlain) continue;
                    var grid = p.Controls.OfType<TableLayoutPanel>().FirstOrDefault();
                    bool cap = tag == LookupCaptioned;
                    p.Height = _inputH + (cap ? CapH : 0);
                    if (grid != null)
                    {
                        grid.RowStyles[0].Height = _inputH;
                        if (cap && grid.RowStyles.Count > 1) grid.RowStyles[1].Height = CapH;
                    }
                }
            }

            // Parents-married toggle row.
            pnlParentsMarried.Height = Math.Max(_inputH, 34);
            tglParentsMarried.Top = (pnlParentsMarried.Height - tglParentsMarried.Height) / 2;
            lblParentsMarriedState.Top = 0;
            lblParentsMarriedState.Height = pnlParentsMarried.Height;
            // The sentence beside the toggle is long; let its panel span the value columns.
            tblMarriage.SetColumnSpan(pnlParentsMarried, 3);
            pnlParentsMarried.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            lblParentsMarriedState.Left = tglParentsMarried.Right + 12;
            lblParentsMarriedState.Width = 700;
            lblParentsMarriedState.AutoEllipsis = true;

            // The at-a-glance rail and the step strip.
            if (_wizardBody != null) _wizardBody.ColumnStyles[1].Width = wide == 1 ? 360 : 310;
            if (_stepStrip != null)
            {
                // A constant, never read back: the cell lays the strip out minus its margins, so reading
                // Height back and writing it into the row shrinks the strip a little on every pass.
                int stripH = tier == 2 ? 64 : 76;
                _stepStrip.Margin = new Padding(0);
                _stepStrip.Height = stripH;
                if (_wizardRoot != null) _wizardRoot.RowStyles[0].Height = stripH;
            }

            LayoutEntryChrome(tier);
            PositionHiddenTabHeader();

            tabControl.ResumeLayout(true);
            _entryDialog.ResumeLayout(true);
            RefreshRail();
        }

        private void AlignInRow(Control c, bool top)
        {
            if (!top) return;
            if (c is Label)
            {
                c.Dock = DockStyle.Top;
                c.Padding = new Padding(0);
                c.Height = _inputH + InputPad;   // level with the input, which has a 3px margin above
                ((Label)c).TextAlign = ContentAlignment.MiddleLeft;
            }
            else if (!(c is TableLayoutPanel))
            {
                c.Anchor = (c.Anchor | AnchorStyles.Top) & ~AnchorStyles.Bottom;
            }
        }

        /// <summary>Header, footer buttons and the popup's own spacing for the current tier.</summary>
        private void LayoutEntryChrome(int tier)
        {
            lblTitle.Font = Px(PxTitle, FontStyle.Bold);
            lblSubtitle.Font = Px(PxSub);
            chkDelayed.Font = Px(PxLabel);

            lblTitle.Location = new Point(0, 0);
            lblSubtitle.Location = new Point(2, 48);
            if (tier == 2)
            {
                // A short screen: the subtitle and the delayed tick share one line.
                chkDelayed.Location = new Point(lblSubtitle.Left + lblSubtitle.PreferredSize.Width + 36, 48);
            }
            else
            {
                chkDelayed.Location = new Point(2, 48 + lblSubtitle.PreferredSize.Height + 6);
            }

            if (_entryRoot != null)
                _entryRoot.RowStyles[0].Height = tier == 2 ? 86 : tier == 1 ? 112 : 120;

            int bh = tier == 2 ? 50 : 56;
            foreach (Button b in new Button[] { btnSubmit, _btnClearForm, _btnPrintFooter })
            {
                if (b == null) continue;
                b.Font = Px(PxButton, FontStyle.Bold);
                b.Height = bh;
            }
            if (btnSubmit != null) btnSubmit.Width = Math.Max(300, TextRenderer.MeasureText(btnSubmit.Text, btnSubmit.Font).Width + 64);
            if (_btnClearForm != null) { _btnClearForm.Width = 150; _btnClearForm.Margin = new Padding(12, 0, 0, 0); }
            if (_btnPrintFooter != null)
            {
                _btnPrintFooter.Width = Math.Max(260, TextRenderer.MeasureText(_btnPrintFooter.Text, _btnPrintFooter.Font).Width + 64);
                _btnPrintFooter.Margin = new Padding(12, 0, 0, 0);
            }
            if (_entryFooter != null) _entryFooter.Padding = new Padding(0, tier == 2 ? 6 : 12, 0, 0);
        }

        // ------------------------------------------------------------------ at-a-glance rail
        private static Label RailCap(string text)
        {
            return new Label
            {
                Text = (text ?? "").ToUpperInvariant(), AutoSize = true, Font = Px(PxHint, FontStyle.Bold),
                ForeColor = UiTheme.Muted, BackColor = Color.Transparent, Margin = new Padding(0, 10, 0, 6), UseMnemonic = false
            };
        }

        private static Control RailKv(string key, string value)
        {
            var t = new TableLayoutPanel { Dock = DockStyle.Top, Height = 38, ColumnCount = 2, BackColor = Color.Transparent, Margin = new Padding(0) };
            // The caption takes what it needs and never wraps; the value gets the rest and ellipsizes.
            t.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            var k = new Label { Text = key, AutoSize = true, Anchor = AnchorStyles.Left, Margin = new Padding(0, 0, 10, 0), Font = Px(17f), ForeColor = UiTheme.Muted, TextAlign = ContentAlignment.MiddleLeft, UseMnemonic = false };
            var v = new Label { Text = value, AutoSize = false, Dock = DockStyle.Fill, Font = Px(17f, FontStyle.Bold), ForeColor = UiTheme.Ink, TextAlign = ContentAlignment.MiddleRight, AutoEllipsis = true, UseMnemonic = false };
            t.Controls.Add(k, 0, 0);
            t.Controls.Add(v, 1, 0);
            t.Paint += (s, e) => { using (var p = new Pen(UiTheme.RowLine)) e.Graphics.DrawLine(p, 0, t.Height - 1, t.Width, t.Height - 1); };
            return t;
        }

        // ------------------------------------------------------------------ list screen
        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        private static extern IntPtr SendMessage(IntPtr hWnd, int msg, IntPtr wParam, string lParam);
        private const int EM_SETCUEBANNER = 0x1501;

        private bool _listStyled;

        /// <summary>
        /// Readable type and touch-sized controls on the list screen. Runs after the shell has
        /// styled the grids (UiTheme.Polish sets its own grid fonts the first time the module is
        /// shown), so it has the last word.
        /// </summary>
        private void ApplyListLayout()
        {
            lblTitle.Font = Px(PxTitle, FontStyle.Bold);
            lblSubtitle.Font = Px(PxSub);
            lblSubtitle.Location = new Point(2, 48);
            chkDelayed.Font = Px(PxLabel);

            layoutMain.RowStyles[0].Height = 90;

            btnNewRegistration.Font = Px(PxButton, FontStyle.Bold);
            btnOpenRecord.Font = Px(PxButton);
            btnNewRegistration.Size = new Size(Math.Max(300, TextRenderer.MeasureText(btnNewRegistration.Text, btnNewRegistration.Font).Width + 56), 52);
            btnOpenRecord.Size = new Size(190, 52);
            btnNewRegistration.Margin = new Padding(12, 6, 0, 6);
            btnOpenRecord.Margin = new Padding(6, 6, 0, 6);

            layoutRecords.RowStyles[0].Height = 66;
            layoutRecords.RowStyles[1].Height = 56;
            txtSearch.Font = Px(PxInput);
            btnClearSearch.Font = Px(PxButton);
            btnClearSearch.Size = new Size(110, 46);
            txtSearch.Margin = new Padding(3, 4, 8, 0);
            btnClearSearch.Margin = new Padding(0, 0, 0, 0);
            if (txtSearch.IsHandleCreated) SendMessage(txtSearch.Handle, EM_SETCUEBANNER, (IntPtr)1, "Search by registry number, name, sex or status");

            foreach (Label l in AllDescendants(cardRecords).OfType<Label>())
                if (l.Text == "RECENT BIRTH REGISTRATIONS" || l.Text == "PENDING APPROVAL")
                    l.Font = Px(PxLabel, FontStyle.Bold);

            if (_dgvPending != null) _dgvPending.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.None;
            ReapplyListGrids();

            if (_dgvPending != null)
            {
                _btnApprovePending.Font = Px(PxButton, FontStyle.Bold);
                _btnApprovePending.Height = 52;
                var pr = _btnApprovePending.Parent as TableLayoutPanel;
                if (pr != null && pr.RowStyles.Count >= 3)
                {
                    pr.RowStyles[0].Height = 40;
                    pr.RowStyles[2].Height = 60;
                }
            }
            _listStyled = true;
        }

        /// <summary>Re-applies column weights and row height; binding a new table rebuilds the columns.</summary>
        private void ReapplyListGrids()
        {
            StyleListGrid(dgvBirths, new Dictionary<string, float>
            {
                { "Registry No", 15 }, { "Child", 38 }, { "Sex", 8 }, { "DOB", 13 }, { "Book", 9 }, { "Page", 7 }, { "Status", 13 }
            });
            if (_dgvPending != null)
            {
                StyleListGrid(_dgvPending, new Dictionary<string, float>
                {
                    { "Registry No", 26 }, { "Child", 34 }, { "Sex", 11 }, { "DOB", 15 }, { "Submitted", 18 }
                });
                // The side list is narrow: one step smaller so its headings are not cut off.
                _dgvPending.DefaultCellStyle.Font = Px(16f);
                _dgvPending.ColumnHeadersDefaultCellStyle.Font = Px(16f, FontStyle.Bold);
                _dgvPending.ColumnHeadersDefaultCellStyle.Padding = new Padding(4, 0, 4, 0);
            }
        }

        private static IEnumerable<Control> AllDescendants(Control root)
        {
            foreach (Control c in root.Controls)
            {
                yield return c;
                foreach (Control d in AllDescendants(c)) yield return d;
            }
        }

        private static void StyleListGrid(DataGridView g, IDictionary<string, float> weights)
        {
            g.DefaultCellStyle.Font = Px(PxGrid);
            g.ColumnHeadersDefaultCellStyle.Font = Px(PxGrid, FontStyle.Bold);
            g.ColumnHeadersHeight = 52;
            g.RowTemplate.Height = 46;
            foreach (DataGridViewRow r in g.Rows) r.Height = 46;
            g.ColumnHeadersDefaultCellStyle.WrapMode = DataGridViewTriState.False;
            // The id is only the lookup key. Left visible it takes a column's share of the width.
            if (g.Columns.Contains("id")) g.Columns["id"].Visible = false;
            g.ShowCellToolTips = true;
            foreach (DataGridViewColumn col in g.Columns)
            {
                float w;
                if (weights.TryGetValue(col.Name, out w) || weights.TryGetValue(col.HeaderText, out w)) col.FillWeight = w;
            }
        }
    }
}
