// BirthRegistrationForm.Child.cs - the entry tabs brought into the order and wording of Municipal
// Form 102 (Revised January 2007), plus the pieces the form carries and CROMS did not:
//   * time of birth and the hospital's own address (house no. / street, barangay),
//   * item 5b "if multiple birth, child was ...",
//   * birth order as 1st, 2nd, 3rd ... (a pick-list, never free text),
//   * the registration fee typed directly on the form (Treasury O.R. + amount),
//   * the informant pre-filled from the father's own particulars.
//
// Built in code, not the Designer: this form's Designer file has been regenerated by Visual
// Studio before and silently dropped hand-added controls. Everything here runs BEFORE
// InitializeLookupControls (it moves the placeholder text boxes that method turns into
// dropdown cells), except where a method says otherwise.

using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Windows.Forms;
using CROMS.Data;
using CROMS.Modules;
using MySql.Data.MySqlClient;

namespace CROMS.Forms
{
    /// <summary>Birth order as the paper form writes it: 1st, 2nd, 3rd ...</summary>
    internal static class BirthOrderText
    {
        public const int Max = 20;

        public static string Ordinal(int n)
        {
            int t = n % 100;
            string s = (t >= 11 && t <= 13) ? "th" : (n % 10 == 1 ? "st" : n % 10 == 2 ? "nd" : n % 10 == 3 ? "rd" : "th");
            return n + s;
        }

        public static IEnumerable<string> Items()
        {
            for (int i = 1; i <= Max; i++) yield return Ordinal(i);
        }

        private static readonly string[] Words =
        {
            "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth", "tenth",
            "eleventh", "twelfth", "thirteenth", "fourteenth", "fifteenth", "sixteenth", "seventeenth",
            "eighteenth", "nineteenth", "twentieth"
        };

        /// <summary>
        /// "First", "1", "01" and "1st" all become "1st". Anything that is none of those is
        /// returned exactly as it was read - never guessed at.
        /// </summary>
        public static string Normalize(string text)
        {
            if (string.IsNullOrWhiteSpace(text)) return "";
            string t = text.Trim();
            int w = Array.IndexOf(Words, t.ToLowerInvariant());
            if (w >= 0) return Ordinal(w + 1);
            string digits = t.ToLowerInvariant();
            foreach (string suffix in new[] { "st", "nd", "rd", "th" })
                if (digits.EndsWith(suffix, StringComparison.Ordinal)) { digits = digits.Substring(0, digits.Length - 2); break; }
            int n;
            if (int.TryParse(digits, NumberStyles.None, CultureInfo.InvariantCulture, out n) && n >= 1 && n <= Max)
                return Ordinal(n);
            return t;
        }
    }

    public partial class BirthRegistrationForm
    {
        // ---- Child tab additions
        private Label lblTimeOfBirth, lblPlaceAddr, lblMultiple;
        private DateTimePicker dtpTimeOfBirth;
        private TextBox txtPlaceAddr;                 // placeholder, replaced by the two cells below
        private ComboBox cboMultiple;
        private ComboBox _hospBarangay, _hospHouse;   // hospital address: barangay, house no. / street
        private string _timeRaw;                      // a stored time that is not a clock time, kept so a save never erases it

        // ---- Certification tab: the registration fee
        private Label lblFee, lblFeeOr, lblFeeNote;
        private TextBox txtFee, txtFeeOr;
        private bool _feeRecorded;                    // this record already has its fee in the payment log

        // ---- Informant tab: pre-filled from the father
        private Label lblInformantHint;
        private bool _informantAutoFilled, _suppressInformantFill;
        private string _informantFilledName = "";

        // ------------------------------------------------------------------ small helpers
        private static void PlaceCell(TableLayoutPanel t, Control c, int col, int row)
        {
            t.Controls.Add(c, col, row);
            t.SetColumn(c, col);
            t.SetRow(c, row);
        }

        private static Label CaptionLike(Label like, string text)
        {
            return new Label
            {
                Text = text,
                Dock = DockStyle.Fill,
                Font = like.Font,
                ForeColor = like.ForeColor,
                TextAlign = ContentAlignment.MiddleLeft,
                Margin = like.Margin,
                UseMnemonic = false
            };
        }

        private static void SetRows(TableLayoutPanel t, int rows)
        {
            t.RowCount = rows;
            while (t.RowStyles.Count < rows) t.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        }

        // ------------------------------------------------------------------ arrange the tabs
        /// <summary>
        /// Called once from the constructor, before the placeholder text boxes are turned into
        /// dropdown cells. Puts every field where the paper form has it and labels it with the
        /// form's own item number.
        /// </summary>
        private void ArrangeBirthTabs()
        {
            // ---------------- Child: items 1-6, in the form's order
            tblChild.SuspendLayout();
            lblTimeOfBirth = CaptionLike(lblDob, "Time of Birth");
            dtpTimeOfBirth = new DateTimePicker
            {
                Name = "dtpTimeOfBirth",
                Anchor = dtpDob.Anchor,
                Margin = dtpDob.Margin,
                Format = DateTimePickerFormat.Custom,
                CustomFormat = "hh:mm tt",
                ShowCheckBox = true,
                Checked = false,
                Width = Math.Max(dtpDob.Width, 220)
            };
            lblPlaceAddr = CaptionLike(lblPlace, "Hospital Address");
            txtPlaceAddr = new TextBox
            {
                Name = "txtPlaceAddr",
                Anchor = txtPlace.Anchor,
                Margin = txtPlace.Margin,
                Font = txtPlace.Font
            };
            lblMultiple = CaptionLike(lblTypeOfBirth, "5b. If Multiple Birth, Child Was");
            cboMultiple = new ComboBox
            {
                Name = "cboMultiple",
                Anchor = AnchorStyles.Left,
                Margin = cboTypeOfBirth.Margin,
                DropDownStyle = ComboBoxStyle.DropDownList,
                Width = cboTypeOfBirth.Width,
                Enabled = false
            };
            cboMultiple.Items.AddRange(new object[] { "", "1st", "2nd", "3rd", "4th", "5th" });
            cboTypeOfBirth.SelectedIndexChanged += delegate { ApplyMultipleBirth(); };
            cboTypeOfBirth.TextChanged += delegate { ApplyMultipleBirth(); };

            int placeSpan = tblChild.GetColumnSpan(txtPlace);
            SetRows(tblChild, 7);
            PlaceCell(tblChild, lblFirstName, 0, 0); PlaceCell(tblChild, txtFirstName, 1, 0);
            PlaceCell(tblChild, lblMiddleName, 2, 0); PlaceCell(tblChild, txtMiddleName, 3, 0);
            PlaceCell(tblChild, lblLastName, 0, 1); PlaceCell(tblChild, txtLastName, 1, 1);
            PlaceCell(tblChild, lblSex, 2, 1); PlaceCell(tblChild, cboSex, 3, 1);
            PlaceCell(tblChild, lblDob, 0, 2); PlaceCell(tblChild, dtpDob, 1, 2);
            PlaceCell(tblChild, lblTimeOfBirth, 2, 2); PlaceCell(tblChild, dtpTimeOfBirth, 3, 2);
            PlaceCell(tblChild, lblPlace, 0, 3); PlaceCell(tblChild, txtPlace, 1, 3);
            PlaceCell(tblChild, lblPlaceAddr, 0, 4); PlaceCell(tblChild, txtPlaceAddr, 1, 4);
            tblChild.SetColumnSpan(txtPlaceAddr, Math.Max(2, placeSpan));
            PlaceCell(tblChild, lblTypeOfBirth, 0, 5); PlaceCell(tblChild, cboTypeOfBirth, 1, 5);
            PlaceCell(tblChild, lblMultiple, 2, 5); PlaceCell(tblChild, cboMultiple, 3, 5);
            PlaceCell(tblChild, lblBirthOrder, 0, 6); PlaceCell(tblChild, txtBirthOrder, 1, 6);
            PlaceCell(tblChild, lblWeight, 2, 6); PlaceCell(tblChild, txtWeight, 3, 6);

            lblFirstName.Text = "1. First Name";
            lblSex.Text = "2. Sex";
            lblDob.Text = "3. Date of Birth";
            lblPlace.Text = "4. Place of Birth";
            lblTypeOfBirth.Text = "5a. Type of Birth";
            lblBirthOrder.Text = "5c. Birth Order";
            lblWeight.Text = "6. Weight at Birth (grams)";
            tblChild.ResumeLayout(true);

            // ---------------- Mother: items 7-13, the children counts BEFORE occupation and age
            tblMother.SuspendLayout();
            PlaceCell(tblMother, lblMReligion, 0, 2); PlaceCell(tblMother, txtMReligion, 1, 2);
            PlaceCell(tblMother, lblMBornAlive, 2, 2); PlaceCell(tblMother, txtMBornAlive, 3, 2);
            PlaceCell(tblMother, lblMLiving, 0, 3); PlaceCell(tblMother, txtMLiving, 1, 3);
            PlaceCell(tblMother, lblMDead, 2, 3); PlaceCell(tblMother, txtMDead, 3, 3);
            PlaceCell(tblMother, lblMOccupation, 0, 4); PlaceCell(tblMother, txtMOccupation, 1, 4);
            PlaceCell(tblMother, lblMAge, 2, 4); PlaceCell(tblMother, txtMAge, 3, 4);
            lblMFirst.Text = "7. Maiden First Name";
            lblMCitizen.Text = "8. Citizenship";
            lblMReligion.Text = "9. Religion";
            lblMBornAlive.Text = "10a. Total Children Born Alive";
            lblMLiving.Text = "10b. Children Still Living";
            lblMDead.Text = "10c. Born Alive, Now Dead";
            lblMOccupation.Text = "11. Occupation";
            lblMAge.Text = "12. Age at Time of Birth";
            lblMResidence.Text = "13. Residence";
            tblMother.ResumeLayout(true);

            // ---------------- Father: items 14-19 (already in the form's order)
            lblFFirst.Text = "14. First Name";
            lblFCitizen.Text = "15. Citizenship";
            lblFReligion.Text = "16. Religion";
            lblFOccupation.Text = "17. Occupation";
            lblFAge.Text = "18. Age at Time of Birth";
            lblFResidence.Text = "19. Residence";

            // ---------------- Marriage of parents: item 20
            lblMarrDate.Text = "20a. Date of Marriage";
            lblMarrPlace.Text = "20b. Place of Marriage";

            // ---------------- Attendant: item 21. The "Others, specify" box sits NEXT TO the type
            // it belongs to (it used to sit three rows away, hidden until Others was picked, so
            // nobody found it).
            tblAttendant.SuspendLayout();
            SetRows(tblAttendant, 4);
            PlaceCell(tblAttendant, lblAttType, 0, 0); PlaceCell(tblAttendant, cboAttType, 1, 0);
            PlaceCell(tblAttendant, lblAttTypeOther, 2, 0); PlaceCell(tblAttendant, txtAttTypeOther, 3, 0);
            PlaceCell(tblAttendant, lblAttName, 0, 1); PlaceCell(tblAttendant, txtAttName, 1, 1);
            PlaceCell(tblAttendant, lblAttTitle, 2, 1); PlaceCell(tblAttendant, txtAttTitle, 3, 1);
            PlaceCell(tblAttendant, lblAttAddress, 0, 2); PlaceCell(tblAttendant, txtAttAddress, 1, 2);
            tblAttendant.SetColumnSpan(txtAttAddress, 3);
            PlaceCell(tblAttendant, lblAttDate, 0, 3); PlaceCell(tblAttendant, dtpAttDate, 1, 3);
            lblAttType.Text = "21a. Attendant at Birth";
            lblAttName.Text = "21b. Name of Attendant";
            lblAttTitle.Text = "Title / Position";
            lblAttTypeOther.Text = "5. Others, specify";
            txtAttName.Margin = new Padding(3, 3, 24, 3);   // keep "Title / Position" off the name box
            tblAttendant.ResumeLayout(true);

            // ---------------- Informant: item 22, with a line saying when it was pre-filled
            tblInformant.SuspendLayout();
            SetRows(tblInformant, 4);
            lblInformantHint = new Label
            {
                Name = "lblInformantHint",
                Text = "Filled from the father's particulars - change it if someone else reported the birth.",
                Dock = DockStyle.Fill,
                ForeColor = UiTheme.Muted,
                TextAlign = ContentAlignment.MiddleLeft,
                Font = lblInfName.Font,
                Visible = false,
                UseMnemonic = false
            };
            PlaceCell(tblInformant, lblInformantHint, 1, 3);
            tblInformant.SetColumnSpan(lblInformantHint, 3);
            lblInfName.Text = "22. Name of Informant";
            tblInformant.ResumeLayout(true);

            // ---------------- Certification: the registration fee, typed directly
            tblCert.SuspendLayout();
            SetRows(tblCert, 10);
            lblFee = CaptionLike(lblBookPage, "Registration Fee (PHP)");
            txtFee = new TextBox { Name = "txtFee", Anchor = txtBookPage.Anchor, Margin = txtBookPage.Margin, Font = txtBookPage.Font };
            lblFeeOr = CaptionLike(lblBookPage, "Treasury O.R. No.");
            txtFeeOr = new TextBox { Name = "txtFeeOr", Anchor = txtBookPage.Anchor, Margin = txtBookPage.Margin, Font = txtBookPage.Font };
            lblFeeNote = new Label
            {
                Name = "lblFeeNote",
                Dock = DockStyle.Fill,
                ForeColor = UiTheme.Muted,
                TextAlign = ContentAlignment.MiddleLeft,
                Font = new Font(lblBookPage.Font.FontFamily, 8F),   // becomes the hint size in the layout pass
                UseMnemonic = false,
                Text = "Collected at the Treasury. Type the amount and O.R. number; leave both blank if nothing was collected."
            };
            MUi.NumericOnly(txtFee);
            // Fee sits right under Registry Number / Status, where it is seen - not below the fold.
            PlaceCell(tblCert, lblBookPage, 2, 1); PlaceCell(tblCert, txtBookPage, 3, 1);
            PlaceCell(tblCert, lblFee, 0, 2); PlaceCell(tblCert, txtFee, 1, 2);
            PlaceCell(tblCert, lblFeeOr, 2, 2); PlaceCell(tblCert, txtFeeOr, 3, 2);
            PlaceCell(tblCert, lblFeeNote, 1, 3);
            tblCert.SetColumnSpan(lblFeeNote, 3);
            PlaceCell(tblCert, lblPreparedBy, 0, 4); PlaceCell(tblCert, txtPreparedBy, 1, 4);
            PlaceCell(tblCert, lblReceivedBy, 2, 4); PlaceCell(tblCert, txtReceivedBy, 3, 4);
            PlaceCell(tblCert, lblPreparedTitle, 0, 5); PlaceCell(tblCert, txtPreparedTitle, 1, 5);
            PlaceCell(tblCert, lblReceivedTitle, 2, 5); PlaceCell(tblCert, txtReceivedTitle, 3, 5);
            PlaceCell(tblCert, lblPreparedDate, 0, 6); PlaceCell(tblCert, dtpPreparedDate, 1, 6);
            PlaceCell(tblCert, lblReceivedDate, 2, 6); PlaceCell(tblCert, dtpReceivedDate, 3, 6);
            PlaceCell(tblCert, lblRegisteredBy, 0, 7); PlaceCell(tblCert, txtRegisteredBy, 1, 7);
            PlaceCell(tblCert, lblRegisteredTitle, 2, 7); PlaceCell(tblCert, txtRegisteredTitle, 3, 7);
            PlaceCell(tblCert, lblRegisteredDate, 0, 8); PlaceCell(tblCert, dtpRegisteredDate, 1, 8);
            PlaceCell(tblCert, lblRemarks, 0, 9); PlaceCell(tblCert, txtRemarks, 1, 9);
            tblCert.ResumeLayout(true);

            // Informant pre-fill triggers.
            tabControl.SelectedIndexChanged += delegate
            {
                if (tabControl.SelectedTab == tabInformant && CanPrefillInformant()) FillInformantFromFather(false);
            };
            txtInfName.TextChanged += delegate
            {
                if (_suppressInformantFill) return;
                if (_informantAutoFilled && !string.Equals(txtInfName.Text.Trim(), _informantFilledName, StringComparison.Ordinal))
                {
                    _informantAutoFilled = false;
                    lblInformantHint.Visible = false;
                }
            };
        }

        /// <summary>Tab order follows reading order on every tab (the dropdown hosts replaced the
        /// placeholders, so left to themselves they would all tab first).</summary>
        private void OrderBirthTabIndexes()
        {
            foreach (TableLayoutPanel t in EntryTables())
            {
                int i = 1;
                foreach (Control c in t.Controls.Cast<Control>()
                             .OrderBy(c => t.GetRow(c)).ThenBy(c => t.GetColumn(c)))
                    c.TabIndex = i++;
            }
        }

        // ------------------------------------------------------------------ birth order
        /// <summary>Called after the lookup cells exist: birth order becomes a pick-list of
        /// 1st-20th. Typing is not offered - "proper number" means the list, not free text.</summary>
        private void ConfigureBirthOrder()
        {
            _cboBirthOrder.DropDownStyle = ComboBoxStyle.DropDownList;
            _cboBirthOrder.BackColor = Color.White;   // a list box paints grey unless told otherwise
            _cboBirthOrder.Items.Clear();
            _cboBirthOrder.Items.Add("");
            foreach (string s in BirthOrderText.Items()) _cboBirthOrder.Items.Add(s);
        }

        private void SetBirthOrder(string stored)
        {
            string v = BirthOrderText.Normalize(stored);
            if (v.Length == 0) { _cboBirthOrder.SelectedIndex = 0; return; }
            int idx = _cboBirthOrder.Items.IndexOf(v);
            if (idx < 0) { _cboBirthOrder.Items.Add(v); idx = _cboBirthOrder.Items.Count - 1; }  // never hide what a record holds
            _cboBirthOrder.SelectedIndex = idx;
        }

        // ------------------------------------------------------------------ multiple birth (5b)
        private void ApplyMultipleBirth()
        {
            string type = (cboTypeOfBirth.Text ?? "").Trim();
            bool multiple = type.Length > 0 && !string.Equals(type, "Single", StringComparison.OrdinalIgnoreCase);
            lblMultiple.Enabled = multiple;
            cboMultiple.Enabled = multiple;
            if (!multiple) cboMultiple.SelectedIndex = -1;   // a single birth cannot be the 2nd of a set
        }

        private object MultipleBirthParam()
        {
            string v = cboMultiple.Enabled ? (cboMultiple.Text ?? "").Trim() : "";
            return v.Length == 0 ? (object)DBNull.Value : v;
        }

        private void SetMultipleBirth(string stored)
        {
            ApplyMultipleBirth();
            string v = BirthOrderText.Normalize(stored);
            if (v.Length == 0) { cboMultiple.SelectedIndex = -1; return; }
            int idx = cboMultiple.Items.IndexOf(v);
            if (idx < 0) { cboMultiple.Items.Add(v); idx = cboMultiple.Items.Count - 1; }
            cboMultiple.SelectedIndex = idx;
        }

        // ------------------------------------------------------------------ time of birth
        private static readonly string[] TimeFormats =
            { "HH:mm", "H:mm", "hh:mm tt", "h:mm tt", "HH:mm:ss", "h:mm:ss tt", "hh:mmtt", "h:mmtt" };

        /// <summary>Stored as HH:mm (24 h) - what every existing row already holds.</summary>
        private object TimeOfBirthParam()
        {
            if (dtpTimeOfBirth.Checked) return dtpTimeOfBirth.Value.ToString("HH:mm", CultureInfo.InvariantCulture);
            return string.IsNullOrWhiteSpace(_timeRaw) ? (object)DBNull.Value : _timeRaw;
        }

        private void SetTimeOfBirth(string stored)
        {
            _timeRaw = null;
            if (string.IsNullOrWhiteSpace(stored)) { dtpTimeOfBirth.Checked = false; return; }
            DateTime t;
            if (DateTime.TryParseExact(stored.Trim(), TimeFormats, CultureInfo.InvariantCulture, DateTimeStyles.AllowWhiteSpaces, out t))
            {
                dtpTimeOfBirth.Value = DateTime.Today.Add(t.TimeOfDay);
                dtpTimeOfBirth.Checked = true;
            }
            else
            {
                dtpTimeOfBirth.Checked = false;
                _timeRaw = stored.Trim();   // not a clock time: keep it, do not erase it on save
            }
        }

        // ------------------------------------------------------------------ hospital address
        /// <summary>Barangay follows the hospital's municipality, exactly as it does for every
        /// other address on this form.</summary>
        private void WireHospitalAddress()
        {
            GeoLookup.Strict(_hospBarangay, LearningLibrary.Barangay, "barangay", () => _pob[1].Items.Count > 1);
            _pob[1].SelectedIndexChanged += delegate { GeoLookup.Reset(_hospBarangay); };
            _pob[2].SelectedIndexChanged += delegate { GeoLookup.LoadBarangays(_hospBarangay, _pob[1].Text, _pob[2].Text); };
        }

        private void SetHospitalAddress(string house, string barangay)
        {
            // Province and municipality are already selected, which loaded the barangay list.
            GeoLookup.Select(_hospBarangay, barangay);
            _hospHouse.Text = house ?? "";
        }

        // ------------------------------------------------------------------ informant from father
        private bool CanPrefillInformant()
        {
            if (_editingId.HasValue)
            {
                string st = (cboStatus.Text ?? "").Trim();
                if (st.Length > 0 && !string.Equals(st, "Draft", StringComparison.OrdinalIgnoreCase)) return false;
            }
            return true;
        }

        private static bool AllBlank(IEnumerable<ComboBox> cells)
        {
            return cells.All(c => string.IsNullOrWhiteSpace(c.Text));
        }

        /// <summary>
        /// Pre-fills the informant (item 22) from the father (items 14 and 19) - the usual case.
        /// It only ever fills an EMPTY informant: what the operator typed is never overwritten.
        /// A line under the name says it was pre-filled, and changing the name clears that line.
        /// </summary>
        private void FillInformantFromFather(bool relationshipJustChosen)
        {
            if (_suppressInformantFill) return;
            string name = string.Join(" ", new[] { txtFFirst.Text, txtFMiddle.Text, txtFLast.Text }
                .Select(s => (s ?? "").Trim()).Where(s => s.Length > 0));
            if (name.Length == 0) return;

            bool relBlank = string.IsNullOrWhiteSpace(_cboInfRel.Text);
            bool blank = txtInfName.Text.Trim().Length == 0 && AllBlank(_infAddr) && (relationshipJustChosen || relBlank);
            if (!blank && !_informantAutoFilled) return;

            _suppressInformantFill = true;
            try
            {
                txtInfName.Text = name;
                OthersBox.Apply(_cboInfRel, txtInfRelOther, lblInfRelOther, "Father", SetLookup);
                GeoLookup.SetAddress(_infAddr[0], _infAddr[1], _infAddr[2],
                    _fres[1].Text, _fres[2].Text, _fres[3].Text);
                _informantAutoFilled = true;
                _informantFilledName = name;
                lblInformantHint.Visible = true;
            }
            finally { _suppressInformantFill = false; }
        }

        private void cboInfRel_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (_suppressInformantFill) return;
            if (string.Equals((_cboInfRel.Text ?? "").Trim(), "Father", StringComparison.OrdinalIgnoreCase))
                FillInformantFromFather(true);
        }

        private void ResetInformantPrefill()
        {
            _informantAutoFilled = false;
            _informantFilledName = "";
            if (lblInformantHint != null) lblInformantHint.Visible = false;
        }

        // ------------------------------------------------------------------ registration fee
        /// <summary>Shows the fee already recorded for this record (locked: an O.R. is issued
        /// once) or leaves the boxes open for a new one.</summary>
        private void LoadRegistrationFee(int birthId)
        {
            _feeRecorded = false;
            txtFee.ReadOnly = txtFeeOr.ReadOnly = false;
            txtFee.Text = txtFeeOr.Text = "";
            try
            {
                using (DataTable dt = Db.Pull(
                    "SELECT or_number, net_amount FROM payments WHERE source_table = 'births' AND source_id = @id ORDER BY id LIMIT 1",
                    new MySqlParameter("@id", birthId)))
                {
                    if (dt.Rows.Count == 0) return;
                    txtFee.Text = Convert.ToDecimal(dt.Rows[0]["net_amount"]).ToString("0.00", CultureInfo.InvariantCulture);
                    txtFeeOr.Text = Convert.ToString(dt.Rows[0]["or_number"]);
                    txtFee.ReadOnly = txtFeeOr.ReadOnly = true;
                    _feeRecorded = true;
                }
            }
            catch { /* the fee is information here - a read failure must not stop the record opening */ }
        }

        private void ResetRegistrationFee()
        {
            _feeRecorded = false;
            if (txtFee == null) return;
            txtFee.ReadOnly = txtFeeOr.ReadOnly = false;
            txtFee.Text = txtFeeOr.Text = "";
        }

        /// <summary>Inline checks for the fee boxes, folded into ValidateChild.</summary>
        private void ValidateRegistrationFee(Action<Control, TabPage, string[]> flag)
        {
            if (_feeRecorded) return;
            string amt = txtFee.Text.Trim(), or = txtFeeOr.Text.Trim();
            if (amt.Length == 0 && or.Length == 0) return;

            decimal a;
            if (!decimal.TryParse(amt, NumberStyles.Number, CultureInfo.InvariantCulture, out a) || a <= 0)
                flag(txtFee, tabCert, new[] { "Enter the fee amount collected.", "Enter the amount." });
            if (or.Length == 0)
            {
                flag(txtFeeOr, tabCert, new[] { "Enter the Treasury Official Receipt number for this fee.", "Enter the O.R. number." });
                return;
            }
            DataRow dup = PaymentService.FindByOr(or);
            bool mine = dup != null && _editingId.HasValue && (dup["source_table"] as string) == "births" &&
                        dup["source_id"] != DBNull.Value && Convert.ToInt32(dup["source_id"]) == _editingId.Value;
            if (dup != null && !mine)
                flag(txtFeeOr, tabCert, new[] { "O.R. " + or + " is already recorded for another payment.", "O.R. already used." });
        }

        /// <summary>
        /// Writes the typed fee into the payment log, linked to this record. Never for a Draft
        /// (an O.R. is not spent on a record that is not yet official) and only once per record.
        /// A failure is reported but does not undo the registration - the record is already saved
        /// and the fee can be recorded again from Fees &amp; Payments.
        /// </summary>
        private void RecordRegistrationFee(long birthId, string status, IWin32Window owner)
        {
            if (_feeRecorded || string.Equals(status, "Draft", StringComparison.OrdinalIgnoreCase)) return;
            string amt = txtFee.Text.Trim(), or = txtFeeOr.Text.Trim();
            if (amt.Length == 0 && or.Length == 0) return;
            try
            {
                decimal a = decimal.Parse(amt, NumberStyles.Number, CultureInfo.InvariantCulture);
                string child = (txtLastName.Text.Trim() + ", " + txtFirstName.Text.Trim()).Trim(' ', ',');
                var e = new PaymentEntry
                {
                    Source = PaymentService.SourceBirth,
                    SourceTable = "births",
                    SourceId = (int)birthId,
                    PayerName = string.IsNullOrWhiteSpace(txtInfName.Text) ? child : txtInfName.Text.Trim(),
                    Purpose = "Birth registration" + (chkDelayed.Checked ? " (delayed)" : "") + " - " + child,
                    OrNumber = or,
                    Method = "Cash"
                };
                e.Lines.Add(new PaymentLine
                {
                    FeeCode = "REG-BIRTH",
                    Description = "Registration - Birth (Municipal Form 102)" + (chkDelayed.Checked ? " - delayed registration" : ""),
                    Quantity = 1,
                    UnitAmount = a
                });
                PaymentService.RecordForModule(e, Session.User == null ? (int?)null : Session.User.Id);
                _feeRecorded = true;
            }
            catch (Exception ex)
            {
                ErrorLog.Write("BirthRegistrationForm.RecordRegistrationFee", ex);
                // An O.R. already used / bad amount is a rule with its own sentence; anything else is a fault.
                string why = ex is InvalidOperationException ? ex.Message : ErrorLog.Friendly(ex, "record the fee for");
                MessageBox.Show(owner, "The record was saved, but the registration fee was NOT recorded.\n\n" + why +
                    "\n\nRecord it from Fees & Payments (walk-in payment).", "Registration fee",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }
    }
}
