// DeathRegistrationForm.Layout.cs - screen-fitting layout, readable type, inline field messages
// and the footer action bar.
//
// Presentation only. Nothing in here touches SQL, the save path or the business rules; it decides
// how big the entry window is, how large the text is, where a "please fix this" sentence appears,
// and which button in the footer is the one to press next. Kept out of the Designer on purpose:
// this form's Designer has been regenerated by Visual Studio before and silently dropped
// hand-added controls (the same reason BirthRegistrationForm.Layout.cs exists).

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using CROMS.Data;
using CROMS.Modules;

namespace CROMS.Forms
{
    public partial class DeathRegistrationForm
    {
        // ------------------------------------------------------------------ type scale (pixels)
        // Pixel-based so a size means the same thing on every machine: a label is 19, what you type
        // is 20, a button 22, the page title 32. The small hint under a dropdown and a validation
        // sentence are the only things allowed below 19.
        private const float PxTitle = 32f, PxLabel = 19f, PxInput = 20f, PxButton = 22f,
                            PxHint = 16f, PxErr = 17f, PxGrid = 18f;

        private static Font Px(float px, FontStyle st = FontStyle.Regular)
        {
            return new Font("Segoe UI", px, st, GraphicsUnit.Pixel);
        }

        private static float PxOf(Font f)
        {
            return f.Unit == GraphicsUnit.Pixel ? f.Size : f.SizeInPoints * 96f / 72f;
        }

        // ------------------------------------------------------------------ state
        private const int ErrH = 24;        // height reserved under a field that can show a message
        private const int InputPad = 6;     // an input's own 3px margin above and below
        private const int CapH = 22;        // the small caption under each dropdown of a place
        private int _inputH = 34;           // natural height of a one-line input at PxInput
        private int _appliedKey = -1;       // tier + width class last laid out, so a resize storm is cheap
        private bool _fontsApplied;
        private TableLayoutPanel _wizardBody, _wizardRoot, _entryRoot;
        private bool _glowWired;

        private const string LookupCaptioned = "lookup:cap";
        private const string LookupPlain = "lookup:plain";

        private sealed class FieldMsg
        {
            public Label Text;
            public TableLayoutPanel Wrap;
            public Control Cell;
            public Func<bool> IsFixed;      // when set, the message only goes once this says the field is right
            public string[] Variants;       // the wordings last asked for, longest first
        }

        private readonly Dictionary<Control, FieldMsg> _fieldMsgs = new Dictionary<Control, FieldMsg>();

        private IWin32Window MsgOwner
        {
            get { return _entryDialog != null ? (IWin32Window)_entryDialog : this; }
        }

        /// <summary>
        /// Logs the technical detail and tells the person at the keyboard one short sentence.
        /// Never shows exception text, SQL or a stack trace.
        /// </summary>
        private void Fail(Exception ex, string doing, string where)
        {
            ErrorLog.Report(MsgOwner, "DeathRegistration." + where, ex, doing);
        }

        // ------------------------------------------------------------------ entry window size
        /// <summary>
        /// The popup takes most of the usable screen - 92% of it, 97% on a short one such as
        /// 1366x768 - and is centred. It never asks for more than the screen has.
        /// </summary>
        internal static Size EntryDialogSize(Rectangle workArea)
        {
            double wFrac = workArea.Width < 1500 ? 0.97 : 0.92;
            double hFrac = workArea.Height < 900 ? 0.97 : 0.92;
            int w = Math.Min(workArea.Width, Math.Max(900, (int)(workArea.Width * wFrac)));
            int h = Math.Min(workArea.Height, Math.Max(600, (int)(workArea.Height * hFrac)));
            return new Size(w, h);
        }

        // ------------------------------------------------------------------ inline field messages
        /// <summary>
        /// Gives every required field a sentence-sized slot directly underneath it. Run once, after
        /// the lookups have been built into their cells.
        /// </summary>
        private void PrepareFieldMessages()
        {
            if (_fieldMsgs.Count > 0) return;

            AttachFieldMessage(txtLastName, txtLastName);
            AttachFieldMessage(txtFirstName, txtFirstName);
            AttachFieldMessage(cboSex, cboSex);
            AttachFieldMessage(cboCivil, cboCivil);
            AttachFieldMessage(_cboDCit, HostOf(_cboDCit));
            AttachFieldMessage(dtpDob, dtpDob);
            AttachFieldMessage(txtAge, txtAge);

            // Place of death is one block of three boxes, so one message serves province and
            // municipality, and it goes only when both are filled.
            AttachFieldMessage(_pod[1], HostOf(_pod[1]), () => HasText(_pod[1].Text) && HasText(_pod[2].Text));
            FieldMsg place = _fieldMsgs[_pod[1]];
            _fieldMsgs[_pod[2]] = place;
            _pod[2].TextChanged += (s, e) => ClearFieldMessage(_pod[2]);
            _pod[2].SelectedIndexChanged += (s, e) => ClearFieldMessage(_pod[2]);

            AttachFieldMessage(_cboDImm, HostOf(_cboDImm));
            AttachFieldMessage(cboDisposal, cboDisposal);
            AttachFieldMessage(txtDispPlace, txtDispPlace);

            AttachFieldMessage(txtCInfName, txtCInfName);
            AttachFieldMessage(_cboInfRel, HostOf(_cboInfRel));
            AttachFieldMessage(txtCInfAddr, txtCInfAddr);
        }

        private static bool HasText(string s) { return !string.IsNullOrWhiteSpace(s); }

        /// <summary>
        /// Religion sat alone on the last row of the Deceased step while the right half of the
        /// Middle Name row beside it was empty. It moves up into that gap, which saves a whole row
        /// (the step then fits a 1366x768 screen without scrolling) and balances the two columns.
        /// Tab order is renumbered to reading order so the cursor does not skip over it.
        /// </summary>
        private void RearrangeDeceasedTab()
        {
            Control host = HostOf(_cboDRel);
            if (host == null || host.Parent != tblDeceased || tblDeceased.GetRow(host) != 7 || tblDeceased.RowCount != 8) return;

            tblDeceased.Controls.Remove(lblReligion);
            tblDeceased.Controls.Remove(host);
            tblDeceased.Controls.Add(lblReligion, 2, 1);
            tblDeceased.Controls.Add(host, 3, 1);
            tblDeceased.SetColumnSpan(host, 1);
            tblDeceased.RowStyles.RemoveAt(7);
            tblDeceased.RowCount = 7;

            int n = 0;
            for (int r = 0; r < tblDeceased.RowCount; r++)
                for (int c = 0; c < tblDeceased.ColumnCount; c++)
                {
                    Control at = tblDeceased.GetControlFromPosition(c, r);
                    if (at != null) at.TabIndex = n++;
                }
        }

        /// <summary>The host panel a lookup combo was built into (combo -> grid -> host).</summary>
        private static Control HostOf(ComboBox cbo)
        {
            return cbo.Parent == null ? cbo : (cbo.Parent.Parent ?? cbo.Parent);
        }

        /// <summary>
        /// The input moves into a small two-row wrapper that takes its cell: input on top, a
        /// (normally empty) red line below. The slot is reserved, so showing or clearing a message
        /// never moves anything else on the tab.
        /// </summary>
        private void AttachFieldMessage(Control key, Control cell, Func<bool> isFixed = null)
        {
            var tbl = cell.Parent as TableLayoutPanel;
            if (tbl == null) return;
            TableLayoutPanelCellPosition pos = tbl.GetPositionFromControl(cell);
            int span = tbl.GetColumnSpan(cell);
            int tab = cell.TabIndex;

            var wrap = new TableLayoutPanel
            {
                ColumnCount = 1,
                RowCount = 2,
                Margin = new Padding(0),
                Padding = new Padding(0),
                Dock = DockStyle.Top,
                BackColor = Color.Transparent,
                Height = _inputH + InputPad + ErrH
            };
            wrap.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            wrap.RowStyles.Add(new RowStyle(SizeType.Absolute, _inputH + InputPad));
            wrap.RowStyles.Add(new RowStyle(SizeType.Absolute, ErrH));

            var msg = new Label
            {
                AutoSize = false,
                AutoEllipsis = true,
                Dock = DockStyle.Fill,
                ForeColor = UiTheme.Danger,
                Font = Px(PxErr),
                TextAlign = ContentAlignment.TopLeft,
                Margin = new Padding(Math.Max(0, cell.Margin.Left), 2, 0, 0),
                Visible = false,
                UseMnemonic = false
            };

            tbl.Controls.Remove(cell);
            cell.Anchor = cell.Anchor | AnchorStyles.Top;
            wrap.Controls.Add(cell, 0, 0);
            wrap.Controls.Add(msg, 0, 1);
            tbl.Controls.Add(wrap, pos.Column, pos.Row);
            if (span > 1) tbl.SetColumnSpan(wrap, span);
            wrap.TabIndex = tab;

            var fm = new FieldMsg { Text = msg, Wrap = wrap, Cell = cell, IsFixed = isFixed };
            _fieldMsgs[key] = fm;
            wrap.SizeChanged += (s, e) => { if (fm.Text.Visible) Repick(fm); };

            // The message goes the moment the field changes - the clerk is fixing it.
            Action clear = () => ClearFieldMessage(key);
            if (key is TextBox) ((TextBox)key).TextChanged += (s, e) => clear();
            else if (key is ComboBox)
            {
                ((ComboBox)key).SelectedIndexChanged += (s, e) => clear();
                ((ComboBox)key).TextChanged += (s, e) => clear();
            }
            else if (key is DateTimePicker) ((DateTimePicker)key).ValueChanged += (s, e) => clear();
        }

        /// <summary>
        /// Shows one short red sentence under <paramref name="input"/>. The variants run longest
        /// first; the first that fits the column is used, so the text is never cut off.
        /// </summary>
        private void ShowFieldMessage(Control input, params string[] variants)
        {
            FieldMsg m;
            if (input == null || variants == null || variants.Length == 0 || !_fieldMsgs.TryGetValue(input, out m)) return;
            m.Variants = variants;
            Repick(m);
            m.Text.Visible = true;
        }

        /// <summary>
        /// Chooses the longest wording that fits the column as it is NOW. A message shown for a step
        /// that has not been laid out yet (zero width) is re-fitted the moment the step appears.
        /// </summary>
        private static void Repick(FieldMsg m)
        {
            string[] variants = m.Variants;
            if (variants == null || variants.Length == 0) return;
            string pick = variants[0];
            int room = m.Wrap.Width - m.Text.Margin.Left - 4;
            if (room > 60)
            {
                pick = variants[variants.Length - 1];
                foreach (string v in variants)
                    if (TextRenderer.MeasureText(v, m.Text.Font, new Size(int.MaxValue, ErrH), TextFormatFlags.NoPadding).Width <= room)
                    { pick = v; break; }
            }
            m.Text.Text = pick;
        }

        private void ClearFieldMessage(Control input)
        {
            FieldMsg m;
            if (!_fieldMsgs.TryGetValue(input, out m) || !m.Text.Visible) return;
            if (m.IsFixed != null && !m.IsFixed()) return;
            m.Text.Visible = false;
            m.Text.Text = "";
        }

        private void ClearAllFieldMessages()
        {
            foreach (FieldMsg m in _fieldMsgs.Values.Distinct().ToList())
            {
                m.Text.Visible = false;
                m.Text.Text = "";
            }
        }

        /// <summary>Takes the clerk to the step, scrolls the field into view and puts the cursor on it.</summary>
        private void FocusField(Control input, int step)
        {
            if (step >= 0 && step < tabControl.TabPages.Count && tabControl.SelectedIndex != step)
            {
                tabControl.SelectedIndex = step;
                UpdateStepNavigation();
            }
            if (input == null) return;
            for (Control p = input.Parent; p != null; p = p.Parent)
            {
                var sc = p as ScrollableControl;
                if (sc != null && sc.AutoScroll) { sc.ScrollControlIntoView(input); break; }
            }
            input.Focus();
        }

        // ------------------------------------------------------------------ tables, type, sizes
        private TableLayoutPanel[] EntryTables()
        {
            var list = new List<TableLayoutPanel> { tblDeceased, tblCause, tblInformant, tblCertification };
            TableLayoutPanel extra = _extras.Page.Controls.OfType<TableLayoutPanel>().FirstOrDefault();
            if (extra != null) list.Add(extra);
            return list.ToArray();
        }

        private static IEnumerable<Control> AllDescendants(Control root)
        {
            foreach (Control c in root.Controls)
            {
                yield return c;
                foreach (Control d in AllDescendants(c)) yield return d;
            }
        }

        /// <summary>Sets the readable type scale on everything in the entry tabs.</summary>
        private void StyleEntryFonts(Control parent)
        {
            foreach (Control c in parent.Controls)
            {
                // These paint their own text (or have none); they get the scale through their own switch.
                if (c is StepStrip || c is IssueList || c is Banner || c is ToggleSwitch || c is StatusPill) continue;

                if (c is TextBox || c is ComboBox || c is DateTimePicker || c is NumericUpDown || c is MaskedTextBox)
                    c.Font = Px(PxInput);
                else if (c is Label || c is CheckBox || c is RadioButton || c is LinkLabel)
                {
                    float cur = PxOf(c.Font);
                    // Small hints (under a dropdown) become the hint size; headings already larger stay.
                    float target = cur <= 11.5f ? PxHint : (cur >= 24f ? cur : PxLabel);
                    c.Font = Px(target, c.Font.Style);
                }

                if (c is DateTimePicker && (c.Anchor & AnchorStyles.Right) == 0)
                    c.Width = Math.Max(c.Width, 220);   // a date at this size plus its tick box and arrow

                if (c.HasChildren) StyleEntryFonts(c);
            }
            lblAgeNote.Font = Px(PxHint + 1f, FontStyle.Italic);
        }

        private int MeasureInputHeight()
        {
            int h = 0;
            foreach (Control c in new Control[] { txtFirstName, cboSex, dtpDob })
            {
                if (c == null) continue;
                h = Math.Max(h, c.PreferredSize.Height);
            }
            return Math.Max(34, h);
        }

        /// <summary>
        /// A single-line input that is anchored to one side only was designed at a fixed width.
        /// The wide ones (names, dropdowns) now share the column; dates and the age stay narrow.
        /// </summary>
        private void WidenInputs()
        {
            foreach (TableLayoutPanel t in EntryTables())
            {
                foreach (Control c in AllDescendants(t))
                {
                    if (c is DateTimePicker) continue;
                    Panel host = c as Panel;
                    if (host != null && (host.Tag as string == LookupCaptioned || host.Tag as string == LookupPlain))
                    {
                        host.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
                        continue;
                    }
                    if (!(c is TextBox || c is ComboBox)) continue;
                    // Combos built into a lookup grid are docked by that grid, not by us.
                    if (c.Parent is TableLayoutPanel && c.Parent.Parent is Panel &&
                        ((c.Parent.Parent.Tag as string) == LookupCaptioned || (c.Parent.Parent.Tag as string) == LookupPlain))
                        continue;
                    var tb = c as TextBox;
                    if (tb != null && tb.Multiline) continue;
                    if (c.Dock == DockStyle.Fill || c.Dock == DockStyle.Left)
                    {
                        // The medical page docks its boxes to fill the cell, which would stretch a
                        // one-line box to the whole row height. Anchored, it keeps its natural height.
                        c.Dock = DockStyle.None;
                        c.Anchor = AnchorStyles.Left | AnchorStyles.Right;
                        continue;
                    }
                    if (c.Width >= 260 && (c.Anchor & AnchorStyles.Right) == 0) c.Anchor = c.Anchor | AnchorStyles.Right;
                }
            }
        }

        /// <summary>
        /// An editable combo whose value was set from code shows that text highlighted in blue until
        /// it is first focused, which on a record opened for viewing (or an auto-filled one) reads as
        /// if everything were selected for replacement. Cleared on open and on each step change,
        /// because a step's combos only get their native edit box when the step is first shown.
        /// </summary>
        private void DeselectCombos()
        {
            foreach (ComboBox cb in AllDescendants(tabControl).OfType<ComboBox>())
                if (cb.DropDownStyle == ComboBoxStyle.DropDown && !cb.Focused && cb.IsHandleCreated)
                { cb.SelectionStart = 0; cb.SelectionLength = 0; }
        }

        /// <summary>
        /// Applied once, the first time the popup opens: fonts, the measured input height, and the
        /// sizes that follow from it (the reserved message line, the dropdown hosts).
        /// </summary>
        private void ApplyEntryFontsOnce()
        {
            if (_fontsApplied) return;
            _fontsApplied = true;

            tabControl.SuspendLayout();
            foreach (TabPage p in tabControl.TabPages)
            {
                p.AutoScroll = true;
                p.Padding = new Padding(24, 18, 24, 18);
            }
            StyleEntryFonts(tabControl);
            _inputH = MeasureInputHeight();
            // The medical page's table sizes itself to its content, which collapses its percentage
            // columns to the width of the boxes; it has to be as wide as the page like the others.
            foreach (TableLayoutPanel t in EntryTables()) t.AutoSize = false;
            // The medical page has twice the fields of any other and its captions are the longest
            // ("Reviewed by - health officer"), so on a 1366-wide screen its captions are set one
            // step smaller to leave the boxes room for a date.
            TableLayoutPanel medical = _extras.Page.Controls.OfType<TableLayoutPanel>().FirstOrDefault();
            if (medical != null)
            {
                foreach (Label l in medical.Controls.OfType<Label>()) l.Font = Px(PxHint + 1f);
                // Its dates fill their (narrow) cell instead of holding a fixed width that clips the year.
                foreach (DateTimePicker d in medical.Controls.OfType<DateTimePicker>())
                {
                    d.Font = Px(18f);
                    d.Dock = DockStyle.None;
                    d.Anchor = AnchorStyles.Left | AnchorStyles.Right;
                }
            }
            WidenInputs();

            foreach (FieldMsg m in _fieldMsgs.Values.Distinct())
            {
                m.Text.Font = Px(PxErr);
                SizeWrap(m);
            }
            tabControl.ResumeLayout(true);
        }

        private int InnerHeight(Control cell)
        {
            string tag = cell.Tag as string;
            if (tag == LookupCaptioned) return _inputH + CapH + InputPad;
            return _inputH + InputPad;
        }

        private void SizeWrap(FieldMsg m)
        {
            int inner = InnerHeight(m.Cell);
            m.Wrap.RowStyles[0].Height = inner;
            m.Wrap.RowStyles[1].Height = ErrH;
            m.Wrap.Height = inner + ErrH;
        }

        /// <summary>
        /// Spacing that follows the height we were given. A tall window gets roomy rows; a short one
        /// (1366x768) falls to tighter rows - the text size never changes. Below what even the tightest
        /// rows need, the tab simply scrolls rather than squashing.
        /// </summary>
        private void ApplyEntryTier()
        {
            if (_entryDialog == null || !_fontsApplied) return;
            Size cs = _entryDialog.ClientSize;
            int tier = cs.Height >= 900 ? 0 : cs.Height >= 780 ? 1 : 2;
            int wide = cs.Width >= 1500 ? 1 : 0;
            int key = tier * 10 + wide;
            if (key == _appliedKey) return;
            _appliedKey = key;

            int gap = tier == 0 ? 18 : tier == 1 ? 12 : 4;

            _entryDialog.SuspendLayout();
            tabControl.SuspendLayout();
            // A short screen gives back every pixel that is not a field: tighter page padding and a
            // slimmer window margin. The type size never changes.
            foreach (TabPage p in tabControl.TabPages)
                p.Padding = tier == 2 ? new Padding(24, 10, 24, 4) : new Padding(24, 18, 24, 18);
            if (_entryRoot != null) _entryRoot.Padding = tier == 2 ? new Padding(12, 8, 12, 8) : new Padding(16, 12, 16, 12);
            foreach (TableLayoutPanel t in EntryTables()) LayoutTable(t, gap, tier < 2);

            // The at-a-glance rail and the step strip.
            if (_wizardBody != null) _wizardBody.ColumnStyles[1].Width = wide == 1 ? 360 : 310;
            if (_stepStrip != null)
            {
                // A constant, never read back: the cell lays the strip out minus its margins, so reading
                // Height back and writing it into the row shrinks the strip a little on every pass.
                int stripH = tier == 2 ? 64 : 76;
                _stepStrip.Margin = new Padding(0);
                _stepStrip.Height = stripH;
                if (_wizardRoot != null) _wizardRoot.RowStyles[0].Height = stripH;
            }

            LayoutFooter(tier);
            PositionHiddenTabHeader();

            tabControl.ResumeLayout(true);
            _entryDialog.ResumeLayout(true);
            RefreshRail();
        }

        private void LayoutTable(TableLayoutPanel t, int gap, bool uniform)
        {
            // Label columns are as wide as their widest caption, so every field lines up and no
            // caption wraps or is cut. A note spanning several columns is not a caption.
            foreach (int col in new[] { 0, 2 })
            {
                if (col >= t.ColumnStyles.Count) continue;
                int w = 0;
                foreach (Control c in t.Controls)
                {
                    var l = c as Label;
                    if (l == null || c == lblAgeNote || t.GetColumn(c) != col || t.GetColumnSpan(c) > 1) continue;
                    w = Math.Max(w, TextRenderer.MeasureText(l.Text ?? "", l.Font, new Size(int.MaxValue, 100), TextFormatFlags.NoPadding).Width);
                }
                // The second caption column also carries a left gutter, so a caption never touches
                // the input beside it in the first column.
                int gutter = col == 2 ? 24 : 0;
                t.ColumnStyles[col].SizeType = SizeType.Absolute;
                int cap = t.Parent == _extras.Page ? 250 : 330;
                t.ColumnStyles[col].Width = (w == 0 ? 24 : Math.Max(150, Math.Min(cap, w + 28))) + gutter;
                if (gutter > 0)
                    foreach (Control c in t.Controls)
                        if (c is Label && c != lblAgeNote && t.GetColumn(c) == col)
                            c.Margin = new Padding(gutter, c.Margin.Top, c.Margin.Right, c.Margin.Bottom);
            }
            // The two value columns share what is left, so the form fills the window instead of
            // leaving the right half empty.
            foreach (int col in new[] { 1, 3 })
            {
                if (col >= t.ColumnStyles.Count) continue;
                t.ColumnStyles[col].SizeType = SizeType.Percent;
                t.ColumnStyles[col].Width = 50;
            }

            // Dropdown hosts (citizenship, religion, the place triple ...): same height as an input.
            foreach (Panel p in AllDescendants(t).OfType<Panel>())
            {
                string tag = p.Tag as string;
                if (tag != LookupCaptioned && tag != LookupPlain) continue;
                bool cap = tag == LookupCaptioned;
                p.Margin = new Padding(3);
                p.Height = _inputH + (cap ? CapH : 0);
                var grid = p.Controls.OfType<TableLayoutPanel>().FirstOrDefault();
                if (grid != null)
                {
                    grid.RowStyles[0].Height = _inputH;
                    if (cap && grid.RowStyles.Count > 1) grid.RowStyles[1].Height = CapH;
                }
            }
            foreach (FieldMsg m in _fieldMsgs.Values.Distinct()) SizeWrap(m);

            bool tableHasMessages = _fieldMsgs.Values.Any(m => m.Wrap.Parent == t);
            for (int r = 0; r < t.RowCount && r < t.RowStyles.Count; r++)
            {
                var kids = new List<Control>();
                foreach (Control c in t.Controls) if (t.GetRow(c) == r) kids.Add(c);

                int h = 0;
                bool top = false, anyWrapped = false, anyInput = false;
                foreach (Control c in kids)
                {
                    if (c is Label) continue;
                    anyInput = true;
                    int ch = _inputH + InputPad;
                    FieldMsg wrapped = _fieldMsgs.Values.FirstOrDefault(m => m.Wrap == c);
                    Panel p = c as Panel;
                    TextBox tb = c as TextBox;
                    if (wrapped != null) { ch = wrapped.Wrap.Height; top = true; anyWrapped = true; }
                    else if (p != null && (p.Tag as string) == LookupCaptioned) { ch = InnerHeight(p); top = true; }
                    else if (tb != null && tb.Multiline) { ch = Math.Max(_inputH * 3, 120); top = true; }
                    h = Math.Max(h, ch);
                }
                if (h == 0) h = _inputH + InputPad;
                // On a roomy window every row keeps the same rhythm: a row with no message slot gets
                // the same breathing space, so the rows do not bunch up next to ones that have a slot.
                if (uniform && anyInput && !anyWrapped && tableHasMessages) { h += ErrH; top = true; }
                t.RowStyles[r].SizeType = SizeType.Absolute;
                t.RowStyles[r].Height = h + gap;
                foreach (Control c in kids) AlignInRow(c, top, t);
            }

            // A Dock=Top table does not grow with its rows; without this everything past the old
            // designed height is cut off.
            int total = 0;
            for (int r = 0; r < t.RowCount && r < t.RowStyles.Count; r++) total += (int)t.RowStyles[r].Height;
            if (!t.AutoSize) t.Height = total + t.Padding.Vertical + 8;
        }

        private void AlignInRow(Control c, bool top, TableLayoutPanel t)
        {
            if (c == lblAgeNote)
            {
                // The note beside the age box may need two lines on a narrow window.
                c.Dock = DockStyle.Fill;
                lblAgeNote.TextAlign = ContentAlignment.TopLeft;
                lblAgeNote.Padding = new Padding(0, 5, 0, 0);
                return;
            }
            if (!top) return;
            if (c is Label)
            {
                c.Dock = DockStyle.Top;
                c.Padding = new Padding(0);
                c.Height = _inputH + InputPad;   // level with the input, which has a 3px margin above
                ((Label)c).TextAlign = ContentAlignment.MiddleLeft;
            }
            else if (!(c is TableLayoutPanel))
            {
                c.Anchor = (c.Anchor | AnchorStyles.Top) & ~AnchorStyles.Bottom;
            }
        }

        // ------------------------------------------------------------------ footer action bar
        private static readonly Color SecondaryFill = Color.FromArgb(238, 241, 246);

        /// <summary>Paints a footer button in the given fill and ink; hover and press are darker shades of the fill.</summary>
        private static void Restyle(Button b, Color fill, Color ink, bool solid)
        {
            if (b == null) return;
            b.BackColor = fill;
            b.ForeColor = ink;
            b.FlatAppearance.MouseOverBackColor = UiTheme.Mix(fill, Color.Black, solid ? 0.10f : 0.06f);
            b.FlatAppearance.MouseDownBackColor = UiTheme.Mix(fill, Color.Black, solid ? 0.20f : 0.12f);
            b.Invalidate();
        }

        /// <summary>
        /// Sizes the bottom-right action bar. The save button is the widest and largest type on the
        /// screen, because it is the one thing the clerk came here to press.
        /// </summary>
        private void LayoutFooter(int tier)
        {
            int bh = tier == 2 ? 44 : 56;
            if (_wizardRoot != null) _wizardRoot.RowStyles[2].Height = bh + (tier == 2 ? 10 : 22);

            lblStepHint.Font = Px(tier == 2 ? 17f : 18f);
            lblStepHint.AutoEllipsis = true;

            foreach (Button b in new Button[] { btnBack, btnNext })
            {
                b.Font = Px(PxButton, FontStyle.Bold);
                b.Height = bh;
                b.Margin = new Padding(10, 0, 0, 0);
            }
            // On a short (1366-wide) screen a saved record shows all five buttons at once, so the
            // widths come down a little there rather than the leftmost one running off the card.
            bool narrow = tier == 2;
            btnBack.Width = narrow ? 120 : 140;
            btnNext.Width = narrow ? 140 : 160;

            btnSave.Font = Px(24f, FontStyle.Bold);
            btnSave.Height = bh;
            btnSave.Width = Math.Max(narrow ? 270 : 320, TextRenderer.MeasureText(btnSave.Text, btnSave.Font).Width + 72);
            btnSave.Margin = new Padding(narrow ? 12 : 18, 0, 0, 0);

            btnCertificate.Font = Px(narrow ? 18f : 19f, FontStyle.Bold);
            btnCertificate.Height = bh;
            btnCertificate.Width = TextRenderer.MeasureText(btnCertificate.Text, btnCertificate.Font).Width + (narrow ? 24 : 44) + 34;
            btnCertificate.Margin = new Padding(narrow ? 8 : 10, 0, 0, 0);

            btnAckSlip.Font = Px(narrow ? 18f : 19f, FontStyle.Bold);
            btnAckSlip.Height = bh;
            btnAckSlip.Width = TextRenderer.MeasureText(btnAckSlip.Text, btnAckSlip.Font).Width + (narrow ? 28 : 44);
            btnAckSlip.Margin = new Padding(narrow ? 8 : 10, 0, 0, 0);
            btnBack.Margin = btnNext.Margin = new Padding(narrow ? 8 : 10, 0, 0, 0);

            pnlRecordActions.Padding = new Padding(0, tier == 2 ? 4 : 8, 0, 0);
        }

        /// <summary>
        /// Says, by colour and size, which button is next. While required entries are missing the
        /// solid blue button is Next; the moment they are all filled the solid green, pulsing button
        /// is Register Death (or Save Changes) and Next steps back to a quiet chip.
        /// </summary>
        private void UpdateFooterEmphasis()
        {
            if (btnSave == null || btnNext == null) return;
            bool ready = IsReadyToSave();

            if (!_glowWired)
            {
                _glowWired = true;
                NextStepGlow.Wire(btnSave, 8, UiTheme.Mix(UiTheme.Success, Color.Black, 0.45f));
            }

            // Ready: Register is the one solid green button. Not ready: it is a pale-blue button
            // (visibly a button, but not shouting) and the solid one is Next.
            if (ready) Restyle(btnSave, UiTheme.Success, Color.White, true);
            else Restyle(btnSave, UiTheme.AccentTint, UiTheme.Accent, false);
            if (ready) Restyle(btnNext, SecondaryFill, UiTheme.Ink, false);
            else Restyle(btnNext, UiTheme.Accent, Color.White, true);
            // Only an unsaved registration pulses: it is the "you can finish now" signal. A saved
            // record opened for correction stays solid green without drawing the eye all the time.
            NextStepGlow.SetActive(btnSave, ready && _editingId == null && btnSave.Visible);

            lblStepHint.ForeColor = ready ? UiTheme.Success : UiTheme.Muted;
        }

        private string FooterHint(int cur, int last)
        {
            if (_editingId != null)
                return IsReadyToSave()
                    ? "Editing a saved record. Press " + SaveCaption() + " when you are done."
                    : "Editing a saved record - the deceased's first and last name are still needed.";
            if (IsReadyToSave())
                return "All required entries are filled in. Press " + SaveCaption() + " to save.";

            int here = cur <= 2 ? IssuesForStep(cur).Count : 0;
            if (here > 0) return here + " required " + (here == 1 ? "entry" : "entries") + " left on this step - shown in red.";
            return cur < last ? "This step is complete. Press Next to continue." : "Last step - review, then press " + SaveCaption() + ".";
        }

        // ------------------------------------------------------------------ at-a-glance rail
        private static Label RailCap(string text)
        {
            return new Label
            {
                Text = (text ?? "").ToUpperInvariant(), AutoSize = true, Font = Px(PxHint, FontStyle.Bold),
                ForeColor = UiTheme.Muted, BackColor = Color.Transparent, Margin = new Padding(0, 10, 0, 6), UseMnemonic = false
            };
        }

        private static Control RailKv(string key, string value)
        {
            var t = new TableLayoutPanel { Dock = DockStyle.Top, Height = 38, ColumnCount = 2, BackColor = Color.Transparent, Margin = new Padding(0) };
            // The caption takes what it needs and never wraps; the value gets the rest and ellipsizes.
            t.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            var k = new Label { Text = key, AutoSize = true, Anchor = AnchorStyles.Left, Margin = new Padding(0, 0, 10, 0), Font = Px(17f), ForeColor = UiTheme.Muted, TextAlign = ContentAlignment.MiddleLeft, UseMnemonic = false };
            var v = new Label { Text = value, AutoSize = false, Dock = DockStyle.Fill, Font = Px(17f, FontStyle.Bold), ForeColor = UiTheme.Ink, TextAlign = ContentAlignment.MiddleRight, AutoEllipsis = true, UseMnemonic = false };
            t.Controls.Add(k, 0, 0);
            t.Controls.Add(v, 1, 0);
            t.Paint += (s, e) => { using (var p = new Pen(UiTheme.RowLine)) e.Graphics.DrawLine(p, 0, t.Height - 1, t.Width, t.Height - 1); };
            return t;
        }

        // ------------------------------------------------------------------ list screen
        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        private static extern IntPtr SendMessage(IntPtr hWnd, int msg, IntPtr wParam, string lParam);
        private const int EM_SETCUEBANNER = 0x1501;

        private bool _listStyled;

        /// <summary>
        /// Readable type and touch-sized controls on the list screen. Runs after the shell has
        /// styled the grids (UiTheme.Polish sets its own grid fonts the first time the module is
        /// shown), so it has the last word. The header is the title alone: the old subtitle only
        /// repeated what the card below it already says.
        /// </summary>
        private void ApplyListLayout()
        {
            lblTitle.Font = Px(PxTitle, FontStyle.Bold);
            lblSubtitle.Visible = false;
            layoutMain.RowStyles[0].Height = 64;

            btnNewRegistration.Font = Px(PxButton, FontStyle.Bold);
            btnNewRegistration.Size = new Size(Math.Max(320, TextRenderer.MeasureText(btnNewRegistration.Text, btnNewRegistration.Font).Width + 56), 52);
            btnNewRegistration.Margin = new Padding(12, 6, 0, 6);

            layoutRecords.RowStyles[0].Height = 66;
            layoutRecords.RowStyles[1].Height = 56;
            lblRecent.Font = Px(PxLabel, FontStyle.Bold);
            lblRecent.Dock = DockStyle.Fill;       // a sentence about a failed load must not be clipped at 600px
            lblRecent.AutoEllipsis = true;
            txtSearch.Font = Px(PxInput);
            btnClearSearch.Font = Px(PxButton);
            btnClearSearch.Size = new Size(110, 46);
            txtSearch.Margin = new Padding(3, 4, 8, 0);
            btnClearSearch.Margin = new Padding(0);
            if (txtSearch.IsHandleCreated) SendMessage(txtSearch.Handle, EM_SETCUEBANNER, (IntPtr)1, "Search by registry number, name or status");

            dgvDeaths.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.None;
            _listStyled = true;
            ReapplyListGrid();
        }

        /// <summary>Re-applies column weights and row height; binding a new table rebuilds the columns.</summary>
        private void ReapplyListGrid()
        {
            DataGridView g = dgvDeaths;
            g.DefaultCellStyle.Font = Px(PxGrid);
            g.ColumnHeadersDefaultCellStyle.Font = Px(PxGrid, FontStyle.Bold);
            g.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
            g.ColumnHeadersHeight = 52;
            g.RowTemplate.Height = 46;
            foreach (DataGridViewRow r in g.Rows) r.Height = 46;
            g.ColumnHeadersDefaultCellStyle.WrapMode = DataGridViewTriState.False;
            // The id is only the lookup key. Left visible it takes a column's share of the width.
            if (g.Columns.Contains("id")) g.Columns["id"].Visible = false;
            g.ShowCellToolTips = true;

            var weights = new Dictionary<string, float>
            {
                { "Registry No", 15 }, { "Deceased", 28 }, { "Age", 7 }, { "Date of Death", 14 },
                { "Book", 8 }, { "Page", 7 }, { "Permit", 12 }, { "Status", 12 }
            };
            foreach (DataGridViewColumn col in g.Columns)
            {
                float w;
                if (weights.TryGetValue(col.Name, out w) || weights.TryGetValue(col.HeaderText, out w)) col.FillWeight = w;
            }
        }
    }
}
