using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using CROMS.Modules;
using MySql.Data.MySqlClient;

namespace CROMS.Forms
{
    /// <summary>
    /// The medical-certificate and permit entries on the front of Municipal Form 103 that the
    /// registry had no place for (migration 57): interval between onset and death, other
    /// significant conditions, maternal condition (19c), external causes (19d), autopsy (20),
    /// attendant (21a) and attendance duration (21b), whether the certifier attended (22) with
    /// title and address, the burial/cremation (24a) and transfer (24b) permits, and the health
    /// officer who reviewed it.
    /// <para/>
    /// Built in CODE as its own tab rather than added to the Designer file: this form's
    /// Designer has been regenerated by Visual Studio from an in-memory copy before, silently
    /// deleting hand-added controls (2026-09-10). The registration form only has to add the tab
    /// and call <see cref="Params"/> / <see cref="Load"/> / <see cref="Clear"/>.
    /// <para/>
    /// Every value is optional; an empty box is stored as NULL ("not stated"), and every date
    /// picker shows its own check box so "no date on this sheet" stays sayable.
    /// </summary>
    internal sealed class DeathExtraFields
    {
        public TabPage Page { get; }

        private readonly TextBox _intImm = Box(), _intAnt = Box(), _intUnd = Box(), _otherCond = Box();
        private readonly ComboBox _maternal = Combo(false, new[]
        {
            "Pregnant, not in labour", "Pregnant, in labour", "Less than 42 days after delivery",
            "42 days to 1 year after delivery", "None of the choices"
        });
        private readonly ComboBox _autopsy = Combo(false, new[] { "Yes", "No" });
        private readonly TextBox _manner = Box(), _extPlace = Box();
        private readonly ComboBox _attendant = Combo(true, new[]
        {
            "Private Physician", "Public Health Officer", "Hospital Authority", "None"
        });
        private readonly DateTimePicker _from = Date(), _to = Date();
        private readonly ComboBox _attended = Combo(false, new[] { "Attended", "Did not attend" });
        private readonly TextBox _certTitle = Box(), _certAddr = Box();
        private readonly TextBox _burialNo = Box(), _transferNo = Box(), _reviewedBy = Box();
        private readonly DateTimePicker _burialDate = Date(), _transferDate = Date(), _reviewedDate = Date();

        public DeathExtraFields()
        {
            Page = new TabPage("Medical && Permits") { BackColor = Color.White, AutoScroll = true, Padding = new Padding(18, 14, 18, 14) };

            var t = new TableLayoutPanel
            {
                Dock = DockStyle.Top, AutoSize = true, ColumnCount = 4,
                BackColor = Color.Transparent, Padding = new Padding(0)
            };
            t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 178F));
            t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 380F));
            t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 178F));
            t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 380F));

            Row(t, "Interval - immediate cause", _intImm, "Interval - antecedent cause", _intAnt);
            Row(t, "Interval - underlying cause", _intUnd, "Other significant conditions", _otherCond);
            Row(t, "Maternal condition (19c)", _maternal, "Autopsy (20)", _autopsy);
            Row(t, "Manner of death (19d)", _manner, "External cause place (19d)", _extPlace);
            Row(t, "Attendant (21a)", _attendant, "Certifier attended? (22)", _attended);
            Row(t, "Attended from (21b)", _from, "Attended to (21b)", _to);
            Row(t, "Certifier - title / position", _certTitle, "Certifier - address", _certAddr);
            Row(t, "Burial permit no. (24a)", _burialNo, "Permit date issued (24a)", _burialDate);
            Row(t, "Transfer permit no. (24b)", _transferNo, "Permit date issued (24b)", _transferDate);
            Row(t, "Reviewed by - health officer", _reviewedBy, "Date reviewed", _reviewedDate);

            Page.Controls.Add(t);
        }

        // ---------------------------------------------------------------- SQL glue
        private static readonly string[] Cols =
        {
            "interval_immediate", "interval_antecedent", "interval_underlying", "other_conditions",
            "maternal_condition", "external_manner", "external_place", "autopsy", "attendant_type",
            "attendance_from", "attendance_to", "certifier_attended", "certifier_title", "certifier_address",
            "burial_permit_no", "burial_permit_date", "transfer_permit_no", "transfer_permit_date",
            "reviewed_by", "reviewed_by_date"
        };

        /// <summary>Column list to append to the form's INSERT column list.</summary>
        public static string Columns => string.Join(", ", Cols);
        /// <summary>Matching parameter list for the INSERT VALUES.</summary>
        public static string Placeholders => string.Join(", ", Cols.Select(c => "@x_" + c));
        /// <summary>Assignments to append to the form's UPDATE SET clause.</summary>
        public static string SetClause => string.Join(", ", Cols.Select(c => c + "=@x_" + c));

        public MySqlParameter[] Params()
        {
            object attended = _attended.SelectedIndex == 0 ? 1 : _attended.SelectedIndex == 1 ? (object)0 : null;
            var values = new object[]
            {
                N(_intImm.Text), N(_intAnt.Text), N(_intUnd.Text), N(_otherCond.Text),
                N(_maternal.Text), N(_manner.Text), N(_extPlace.Text), _autopsy.SelectedItem as string,
                N(_attendant.Text), Pick(_from), Pick(_to), attended, N(_certTitle.Text), N(_certAddr.Text),
                N(_burialNo.Text), Pick(_burialDate), N(_transferNo.Text), Pick(_transferDate),
                N(_reviewedBy.Text), Pick(_reviewedDate)
            };
            var ps = new MySqlParameter[Cols.Length];
            for (int i = 0; i < Cols.Length; i++)
                ps[i] = new MySqlParameter("@x_" + Cols[i], values[i] ?? DBNull.Value);
            return ps;
        }

        public void Load(DataRow r)
        {
            Func<string, string> S = c => r.Table.Columns.Contains(c) && r[c] != DBNull.Value ? r[c].ToString() : "";
            _intImm.Text = S("interval_immediate"); _intAnt.Text = S("interval_antecedent");
            _intUnd.Text = S("interval_underlying"); _otherCond.Text = S("other_conditions");
            _maternal.Text = S("maternal_condition");
            _autopsy.SelectedItem = S("autopsy") == "" ? null : S("autopsy");
            _manner.Text = S("external_manner"); _extPlace.Text = S("external_place");
            _attendant.Text = S("attendant_type");
            SetPick(_from, r, "attendance_from"); SetPick(_to, r, "attendance_to");
            string att = S("certifier_attended");
            _attended.SelectedIndex = att == "1" || att == "True" ? 0 : att == "0" || att == "False" ? 1 : -1;
            _certTitle.Text = S("certifier_title"); _certAddr.Text = S("certifier_address");
            _burialNo.Text = S("burial_permit_no"); SetPick(_burialDate, r, "burial_permit_date");
            _transferNo.Text = S("transfer_permit_no"); SetPick(_transferDate, r, "transfer_permit_date");
            _reviewedBy.Text = S("reviewed_by"); SetPick(_reviewedDate, r, "reviewed_by_date");
        }

        public void Clear()
        {
            foreach (TextBox t in new[] { _intImm, _intAnt, _intUnd, _otherCond, _manner, _extPlace, _certTitle,
                                          _certAddr, _burialNo, _transferNo, _reviewedBy }) t.Clear();
            foreach (ComboBox c in new[] { _maternal, _autopsy, _attended }) c.SelectedIndex = -1;
            _attendant.Text = "";
            foreach (DateTimePicker d in new[] { _from, _to, _burialDate, _transferDate, _reviewedDate }) d.Checked = false;
        }

        // ---------------------------------------------------------------- helpers
        private static object N(string s) => string.IsNullOrWhiteSpace(s) ? null : s.Trim();
        private static object Pick(DateTimePicker d) => d.Checked ? (object)d.Value.Date : null;
        private static void SetPick(DateTimePicker d, DataRow r, string col)
        {
            if (r.Table.Columns.Contains(col) && r[col] != DBNull.Value)
            { d.Value = Convert.ToDateTime(r[col]); d.Checked = true; }
            else d.Checked = false;
        }

        private static TextBox Box() => new TextBox { Dock = DockStyle.Fill, Margin = new Padding(0, 3, 12, 3) };

        private static ComboBox Combo(bool editable, IEnumerable<string> items)
        {
            var c = new ComboBox
            {
                Dock = DockStyle.Fill, Margin = new Padding(0, 3, 12, 3),
                DropDownStyle = editable ? ComboBoxStyle.DropDown : ComboBoxStyle.DropDownList
            };
            c.Items.AddRange(items.Cast<object>().ToArray());
            return c;
        }

        private static DateTimePicker Date() => new DateTimePicker
        {
            Format = DateTimePickerFormat.Custom, CustomFormat = "dd MMM yyyy",
            ShowCheckBox = true, Checked = false, Dock = DockStyle.Left, Width = 170, Margin = new Padding(0, 3, 12, 3)
        };

        private static void Row(TableLayoutPanel t, string l1, Control c1, string l2, Control c2)
        {
            int row = t.RowCount++;
            t.RowStyles.Add(new RowStyle(SizeType.Absolute, 31F));
            t.Controls.Add(Cap(l1), 0, row); t.Controls.Add(c1, 1, row);
            t.Controls.Add(Cap(l2), 2, row); t.Controls.Add(c2, 3, row);
        }

        private static Label Cap(string text) => new Label
        {
            Text = text, Dock = DockStyle.Fill, TextAlign = ContentAlignment.MiddleLeft,
            ForeColor = UiTheme.Muted, UseMnemonic = false, BackColor = Color.Transparent
        };
    }
}
